---
title: “Catch”不能出现在“Try”语句之外
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: b5097910fa669c320e2e1b57d8d090b5d66f0956
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 09/23/2020
ms.locfileid: "91074519"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>“Catch”不能出现在“Try”语句之外

`Catch` 必须出现在 `Try...Catch...Finally` 语句块之内。 或是 `Catch` 块中具有不必要的 `Try` ，或是 `Catch` 语句出现在其对应 `Try` 块的边界之外。  
  
 **错误 ID：** BC30380  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
1. 如果 `Catch` 语句不必要，请删除它，或者请将其置于 `Try...Catch...Finally` 语句块之内。  
  
## <a name="see-also"></a>请参阅

- [尝试 .。。Catch .。。Finally 语句](../language-reference/statements/try-catch-finally-statement.md)
